### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by salvagione**
Correcting typos.

### CODE REVIEW

**Comment by bxparks** [comment]
Hi, thanks for the PR. I'm traveling. I Will take a look when I get back.

**Comment by salvagione** [comment]
Nothing earth shattering just a few typos I caught while trying to grok AUnit and TDD. Thank you for publishing your work, you clearly know what you're doing.

**Comment by bxparks** [comment]
Back from vacation! Thanks for the corrections.
AceButton was the first project where I used AUnit. I think my style and techniques have evolved since then. Take a look at the unit tests for [AceTime](https://github.com/bxparks/AceTime/). I think those are better examples of TDD.

**Comment by bxparks** [comment]
Another side comment (in case my opinion matters :-)):  I'm not a fan of TDD. I believe that code should always be tested (using both unit and integration tests). But I do _not_ believe that tests should be written first, then used to drive the development process.

**Comment by salvagione** [comment]
Your opinion matters, if only because you’ve walked the path before me.

If not full TDD, what’s your favorite method?

I have James’ book and I’ve finally got the CppUtest tool chain up and
working. I’m enjoying the TDD methodology so far, especially as I often
don’t have the target hardware right away.

There’s something magical about writing code using just the sensor spec
sheets and compiling off target.

We’ll see if the magic vanishes when the target arrives. Even so, I can’t
imagine it being as bad as it has on the past.

If so let me know.

Best,
Paolo

**Pull request merged**
